# This is a basic workflow to help you get started with Actions

name: SASS

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Code
        uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      # Incomplete
      - name: Install sass.yaml
        run: npm i -g sass

      - name: Check Installation
        run: |
          sass --version
          ls

      - name: Build CSS
        run: "sass styles/src:styles/dist"
